### ISSUE TITLE
加载dsm数据缺失啦

### ISSUE THREAD

**Issue by gaoxiaoxiao** [NichijouCC/cesium_demos#9]
加载dsm数据缺失啦，而且我访问3dtiles都失败了404，我token是的带有3dtiles权限的

**Comment by NichijouCC** [comment]
dsm应该被我清掉了，样例我会再整理一遍；token可以在lib/map.tsx-》MapConfig中修改为自己的token

**Comment by NichijouCC** [comment]
> 加载dsm数据缺失啦，而且我访问3dtiles都失败了404，我token是的带有3dtiles权限的

dsm应该被我清掉了；你要使用自己token可以在src/lib/map.tsx->mapconfig中修改

**Comment by NichijouCC** [comment]
我会再清理一遍样例。ヽ(ー_ー)ノ
